### ISSUE TITLE
Spike: Compare with Python backend framework?

### ISSUE THREAD

**Issue by xiaoxipang** [DynamicTechLab/dv-analyzer#1]
Django/Flask/Pyramid

**Comment by xiaoxipang** [comment]
|Compare Item| Flask | Django |
| --- | --- | --- |
| General | Flask is a Python microframework with the slogan "web development, one drop at a time". The "micro" in "microframework" means that Flask aims to be as simple as possible, yet still extensible. Flask provides simplicity, flexibility and fine-grained control. It is unopinionated (it lets you decide how you want to implement things). | Django prides itself on being the "web framework for perfectionists with deadlines". Django provides an all-inclusive experience: you get an admin panel, database interfaces, an ORM, and directory structure for your apps and projects out of the box. |
| Community | Flask has 35,693 stars and 2,041 watchers on GitHub. It's been forked 10,761 times. | Django has 33,810 stars and 2,017 watchers on GitHub. It's been forked 14,304 times. |
| Company | Pinterest, Twilio, Uber, Netflix, LinkedIn | Bitbucket, Instagram, Pinterest, Disqus, Eventbrite|
| Extendable | Aim to micro, minimal dependencies, but easy to add and change libs | start command, build in default libs, have some learning curve to familar |
| Docker | Base Python Image | Base Python Image |
| ES Connect | py official Python ES Client | Support ES DSL with simple install |

## Conclusion
I personally prefer Flask after reading the docs because it is more microservice-oriented, easier to start and less overhead.

## Reference
1. Flask vs. Django: Why Flask Might Be Better, Feb 13, 2017, https://www.codementor.io/garethdwyer/flask-vs-django-why-flask-might-be-better-4xs7mdf8v
2. Django vs Flask vs Pyramid: Choosing a Python Web Framework, ???, https://www.airpair.com/python/posts/django-flask-pyramid#2-about-the-frameworks
3. Flask Or Django? An In-Depth Comparison | Part One, March 27, 2018, https://scotch.io/bar-talk/flask-or-django-an-in-depth-comparison-part-one
4. Python Elasticsearch Client, https://elasticsearch-py.readthedocs.io/en/master/
5. ElasticSearch with Django the easy way, Jan 13, 2017, https://medium.freecodecamp.org/elasticsearch-with-django-the-easy-way-909375bc16cb
6. Elasticsearch viewable by Flask, Jul 16, 2017, https://dev.to/lukaszkuczynski/elasticsearch-vieable-by-flask

**Comment by menglabs** [comment]
Awesome job, xiaoxi! I agree with you!
I searched job descriptions in Glassdoor and Linkedin with keywords Python/Python web/Python developer, Flask and Django are the most popular frameworks. 

Flask is more lightweight than Django and its micro-framework design is suit for us.
